/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_ioixd_spigotjsongen_WebScraper */

#ifndef _Included_net_ioixd_spigotjsongen_WebScraper
#define _Included_net_ioixd_spigotjsongen_WebScraper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_ioixd_spigotjsongen_WebScraper
 * Method:    getGenerics
 * Signature: (Ljava/lang/String;Ljava/lang/Class;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_net_ioixd_spigotjsongen_WebScraper_getGenerics
  (JNIEnv *, jobject, jstring, jclass);

/*
 * Class:     net_ioixd_spigotjsongen_WebScraper
 * Method:    getMethodGenerics
 * Signature: (Ljava/lang/String;Ljava/lang/Class;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_net_ioixd_spigotjsongen_WebScraper_getMethodGenerics
  (JNIEnv *, jobject, jstring, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
